# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeBooks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BookAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeBooks", llm_response=llm_response, mode="request")
        return typing.cast(types.BookAnalysis, result)

    def AnswerQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Answer:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnswerQuestion", llm_response=llm_response, mode="request")
        return typing.cast(types.Answer, result)

    def ClassifyMessage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[types.Category]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyMessage", llm_response=llm_response, mode="request")
        return typing.cast(typing.List[types.Category], result)

    def DescribeCharacter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CharacterDescription:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DescribeCharacter", llm_response=llm_response, mode="request")
        return typing.cast(types.CharacterDescription, result)

    def ExtractEvents(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Event"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEvents", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.Event"], result)

    def ExtractJsonFromText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractJsonFromText", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, result)

    def GenerateCytoscapeGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CytoscapeJSON:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCytoscapeGraph", llm_response=llm_response, mode="request")
        return typing.cast(types.CytoscapeJSON, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeBooks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BookAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeBooks", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BookAnalysis, result)

    def AnswerQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Answer:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnswerQuestion", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Answer, result)

    def ClassifyMessage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[types.Category]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyMessage", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List[types.Category], result)

    def DescribeCharacter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CharacterDescription:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DescribeCharacter", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CharacterDescription, result)

    def ExtractEvents(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.Event"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEvents", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.Event"], result)

    def ExtractJsonFromText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractJsonFromText", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, result)

    def GenerateCytoscapeGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CytoscapeJSON:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCytoscapeGraph", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CytoscapeJSON, result)

    