# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (23)
# #########################################################################

class Answer(BaseModel):
    answersInText: typing.List["Citation"]
    answer: typing.Optional[str] = None

class BookAnalysis(BaseModel):
    bookNames: typing.List[str]
    popularityOverTime: typing.List["PopularityOverTime"]

class CharacterDescription(BaseModel):
    name: typing.Optional[str] = None
    clothingItems: typing.List[str]
    hairColor: typing.Optional[str] = None
    smellDescription: typing.Optional[str] = None
    spells: typing.List["Spells"]

class Citation(BaseModel):
    documentTitle: typing.Optional[str] = None
    sourceLink: typing.Optional[str] = None
    relevantTextFromDocument: typing.Optional[str] = None
    number: typing.Optional[int] = None

class Company(BaseModel):
    name: typing.Optional[str] = None

class Context(BaseModel):
    documents: typing.List["Document"]

class CytoscapeEdge(BaseModel):
    data: typing.Optional["CytoscapeEdgeData"] = None

class CytoscapeEdgeData(BaseModel):
    id: typing.Optional[str] = None
    source: typing.Optional[str] = None
    target: typing.Optional[str] = None
    label: typing.Optional[str] = None

class CytoscapeJSON(BaseModel):
    elements: typing.Optional["Elements"] = None

class CytoscapeNode(BaseModel):
    data: typing.Dict[str, str]

class Document(BaseModel):
    title: typing.Optional[str] = None
    text: typing.Optional[str] = None
    link: typing.Optional[str] = None

class DynamicOutput(BaseModel):
    model_config = ConfigDict(extra='allow')

class Education(BaseModel):
    school: typing.Optional[str] = None
    degree: typing.Optional[str] = None
    year: typing.Optional[int] = None

class Elements(BaseModel):
    nodes: typing.List["CytoscapeNode"]
    edges: typing.List["CytoscapeEdge"]

class Event(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    link: typing.Optional[str] = None
    speaker: typing.Optional["Speaker"] = None
    datetime: typing.Optional[str] = None

class Message(BaseModel):
    role: typing.Optional[types.Role] = None
    content: typing.Optional[str] = None

class PopularityOverTime(BaseModel):
    bookName: typing.Optional[str] = None
    scores: typing.List["Score"]

class Ranking(BaseModel):
    bookName: typing.Optional[str] = None
    score: typing.Optional[int] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    education: typing.List["Education"]
    skills: typing.List[str]

class Score(BaseModel):
    year: typing.Optional[int] = None
    score: typing.Optional[int] = None

class Speaker(BaseModel):
    name: typing.Optional[str] = None
    title: typing.Optional[str] = None
    company: typing.Optional["Company"] = None

class Spells(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None

class WordCount(BaseModel):
    bookName: typing.Optional[str] = None
    count: typing.Optional[int] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
