# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def AnalyzeBooks(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.BookAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.AnalyzeBooks(input=input,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzeBooks", args={
                "input": input,
            })
            return typing.cast(types.BookAnalysis, result.cast_to(types, types, stream_types, False, __runtime__))
    def AnswerQuestion(self, question: str,context: types.Context,
        baml_options: BamlCallOptions = {},
    ) -> types.Answer:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.AnswerQuestion(question=question,context=context,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnswerQuestion", args={
                "question": question,"context": context,
            })
            return typing.cast(types.Answer, result.cast_to(types, types, stream_types, False, __runtime__))
    def ClassifyMessage(self, convo: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List[types.Category]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ClassifyMessage(convo=convo,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyMessage", args={
                "convo": convo,
            })
            return typing.cast(typing.List[types.Category], result.cast_to(types, types, stream_types, False, __runtime__))
    def DescribeCharacter(self, first_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.CharacterDescription:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.DescribeCharacter(first_image=first_image,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="DescribeCharacter", args={
                "first_image": first_image,
            })
            return typing.cast(types.CharacterDescription, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractEvents(self, raw_text: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Event"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractEvents(raw_text=raw_text,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractEvents", args={
                "raw_text": raw_text,
            })
            return typing.cast(typing.List["types.Event"], result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractJsonFromText(self, input: typing.Union[str, baml_py.Image],
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractJsonFromText(input=input,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractJsonFromText", args={
                "input": input,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, raw_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractResume(raw_text=raw_text,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
                "raw_text": raw_text,
            })
            return typing.cast(types.Resume, result.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateCytoscapeGraph(self, input: typing.Union[str, baml_py.Image],
        baml_options: BamlCallOptions = {},
    ) -> types.CytoscapeJSON:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GenerateCytoscapeGraph(input=input,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateCytoscapeGraph", args={
                "input": input,
            })
            return typing.cast(types.CytoscapeJSON, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeBooks(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.BookAnalysis, types.BookAnalysis]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzeBooks", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[stream_types.BookAnalysis, types.BookAnalysis](
          result,
          lambda x: typing.cast(stream_types.BookAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.BookAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def AnswerQuestion(self, question: str,context: types.Context,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Answer, types.Answer]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnswerQuestion", args={
            "question": question,"context": context,
        })
        return baml_py.BamlSyncStream[stream_types.Answer, types.Answer](
          result,
          lambda x: typing.cast(stream_types.Answer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Answer, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ClassifyMessage(self, convo: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List[types.Category], typing.List[types.Category]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyMessage", args={
            "convo": convo,
        })
        return baml_py.BamlSyncStream[typing.List[types.Category], typing.List[types.Category]](
          result,
          lambda x: typing.cast(typing.List[types.Category], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List[types.Category], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def DescribeCharacter(self, first_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CharacterDescription, types.CharacterDescription]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="DescribeCharacter", args={
            "first_image": first_image,
        })
        return baml_py.BamlSyncStream[stream_types.CharacterDescription, types.CharacterDescription](
          result,
          lambda x: typing.cast(stream_types.CharacterDescription, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CharacterDescription, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractEvents(self, raw_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.Event"], typing.List["types.Event"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractEvents", args={
            "raw_text": raw_text,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.Event"], typing.List["types.Event"]](
          result,
          lambda x: typing.cast(typing.List["stream_types.Event"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.Event"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractJsonFromText(self, input: typing.Union[str, baml_py.Image],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractJsonFromText", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractResume(self, raw_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "raw_text": raw_text,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          result,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateCytoscapeGraph(self, input: typing.Union[str, baml_py.Image],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CytoscapeJSON, types.CytoscapeJSON]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateCytoscapeGraph", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[stream_types.CytoscapeJSON, types.CytoscapeJSON](
          result,
          lambda x: typing.cast(stream_types.CytoscapeJSON, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CytoscapeJSON, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeBooks(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeBooks", args={
            "input": input,
        }, mode="request")
        return result
    def AnswerQuestion(self, question: str,context: types.Context,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnswerQuestion", args={
            "question": question,"context": context,
        }, mode="request")
        return result
    def ClassifyMessage(self, convo: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyMessage", args={
            "convo": convo,
        }, mode="request")
        return result
    def DescribeCharacter(self, first_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DescribeCharacter", args={
            "first_image": first_image,
        }, mode="request")
        return result
    def ExtractEvents(self, raw_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractEvents", args={
            "raw_text": raw_text,
        }, mode="request")
        return result
    def ExtractJsonFromText(self, input: typing.Union[str, baml_py.Image],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractJsonFromText", args={
            "input": input,
        }, mode="request")
        return result
    def ExtractResume(self, raw_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "raw_text": raw_text,
        }, mode="request")
        return result
    def GenerateCytoscapeGraph(self, input: typing.Union[str, baml_py.Image],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateCytoscapeGraph", args={
            "input": input,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeBooks(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeBooks", args={
            "input": input,
        }, mode="stream")
        return result
    def AnswerQuestion(self, question: str,context: types.Context,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnswerQuestion", args={
            "question": question,"context": context,
        }, mode="stream")
        return result
    def ClassifyMessage(self, convo: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyMessage", args={
            "convo": convo,
        }, mode="stream")
        return result
    def DescribeCharacter(self, first_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DescribeCharacter", args={
            "first_image": first_image,
        }, mode="stream")
        return result
    def ExtractEvents(self, raw_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractEvents", args={
            "raw_text": raw_text,
        }, mode="stream")
        return result
    def ExtractJsonFromText(self, input: typing.Union[str, baml_py.Image],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractJsonFromText", args={
            "input": input,
        }, mode="stream")
        return result
    def ExtractResume(self, raw_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "raw_text": raw_text,
        }, mode="stream")
        return result
    def GenerateCytoscapeGraph(self, input: typing.Union[str, baml_py.Image],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateCytoscapeGraph", args={
            "input": input,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))