# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Answer": types.Answer,
    "stream_types.Answer": stream_types.Answer,

    "types.BookAnalysis": types.BookAnalysis,
    "stream_types.BookAnalysis": stream_types.BookAnalysis,

    "types.CharacterDescription": types.CharacterDescription,
    "stream_types.CharacterDescription": stream_types.CharacterDescription,

    "types.Citation": types.Citation,
    "stream_types.Citation": stream_types.Citation,

    "types.Company": types.Company,
    "stream_types.Company": stream_types.Company,

    "types.Context": types.Context,
    "stream_types.Context": stream_types.Context,

    "types.CytoscapeEdge": types.CytoscapeEdge,
    "stream_types.CytoscapeEdge": stream_types.CytoscapeEdge,

    "types.CytoscapeEdgeData": types.CytoscapeEdgeData,
    "stream_types.CytoscapeEdgeData": stream_types.CytoscapeEdgeData,

    "types.CytoscapeJSON": types.CytoscapeJSON,
    "stream_types.CytoscapeJSON": stream_types.CytoscapeJSON,

    "types.CytoscapeNode": types.CytoscapeNode,
    "stream_types.CytoscapeNode": stream_types.CytoscapeNode,

    "types.Document": types.Document,
    "stream_types.Document": stream_types.Document,

    "types.DynamicOutput": types.DynamicOutput,
    "stream_types.DynamicOutput": stream_types.DynamicOutput,

    "types.Education": types.Education,
    "stream_types.Education": stream_types.Education,

    "types.Elements": types.Elements,
    "stream_types.Elements": stream_types.Elements,

    "types.Event": types.Event,
    "stream_types.Event": stream_types.Event,

    "types.Message": types.Message,
    "stream_types.Message": stream_types.Message,

    "types.PopularityOverTime": types.PopularityOverTime,
    "stream_types.PopularityOverTime": stream_types.PopularityOverTime,

    "types.Ranking": types.Ranking,
    "stream_types.Ranking": stream_types.Ranking,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.Score": types.Score,
    "stream_types.Score": stream_types.Score,

    "types.Speaker": types.Speaker,
    "stream_types.Speaker": stream_types.Speaker,

    "types.Spells": types.Spells,
    "stream_types.Spells": stream_types.Spells,

    "types.WordCount": types.WordCount,
    "stream_types.WordCount": stream_types.WordCount,


    "types.Category": types.Category,

    "types.MyEnum": types.MyEnum,

    "types.Role": types.Role,

}